name: Discord Reminder Notify

on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Reminder Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#DB7093"
          username: "Reminder Bot"
          args: "お薬を飲む時間です。飲んだら報告お願いします。🍑🦕🍑🦕"
